gains:
  pos: { x: 1.0, y: 1.0, z: 1.0 }
  vel: { x: 0.3, y: 0.3, z: 0.3 }
  ki: { x: 0.00, y: 0.00, z: 0.00 }
  kib: { x: 0.00, y: 0.00, z: 0.00 }
  rot: { x: 1.0, y: 1.0, z: 1.0 }
  ang: { x: 0.13, y: 0.13, z: 0.1 }

corrections:
  kf: 0.0e-08
  r: 0.0
  p: 0.0

max_pos_int: 0.5
max_pos_int_b: 0.5
