

debug: true
robot_r: 1.0 # map will be dilated in x and y with a radius of [ceil(robot_r/res)] cells
robot_h: 0.5 # map will be dilated in z direction for 2*[ceil(robot_h/res)] cells (if robot_r is set as 0, there will not be any dilation along z either).

global:
  center_x: 0.0
  center_y: 0.0
  range_x: 80.0
  range_y: 80.0
  center_z: 5 
  range_z: 10
  resolution: 0.5 # 3
  num_point_cloud_skip: 1 # integer
  max_raycast_range: 50.0
  dilate_xy: false
  dilate_z: false
  decay_times_to_empty: 50 # number of times of decay to empty, 0 means no decay

local: # local map range z and center_z will be the same as storage map
  # local planning horizon will be from robot to the local voxel map boundary
  range_x: 35.0
  range_y: 35.0
  resolution: 0.25
  max_raycast_range: 30.0
  decay_times_to_empty: 30 # number of times of decay to empty, 0 means no decay

storage: # storage map max_raycat_range will be the same as local map
  center_x: 0.0
  center_y: 0.0
  range_x: 80.0
  range_y: 80.0
  center_z: 5
  range_z: 10.0

