name: docker-build-calibration

# Build calibration when "base" changes, or when any files in the calibration
# folder are modified
# As it is highly improvable that we change code inside the calibration folder,
# it is good to trigger a build once a week to take into account changes in the
# third party repos.
# Additionally, it is good to have a manual trigger button for the build
on:
  workflow_run:
    workflows: ["docker-build-base"]
    branches: [master]
    types:
      - completed
  push:
    paths:
    - 'autonomy_core/calibration/**'
    branches: [master]
  workflow_dispatch:
  # DO NOT add a schedule. This build will be triggered by base schedule.

jobs:
  main:
    runs-on: ubuntu-18.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: kumarrobotics/autonomy:calibration
          file: ./autonomy_core/calibration/Dockerfile
          platforms: linux/amd64,linux/arm64
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
