name: shellcheck-reviewdog
on: [pull_request]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: reviewdog/action-shellcheck@master
      with:
        github_token: ${{ secrets.AUTONOMY_STACK_TOKEN_REVIEWDOG }}
        reporter: github-pr-check
        exclude: "./.git/*"
